spring:
  datasource:
    url: jdbc:mysql://47.92.25.139:3306/${fangcai.db.name}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: ${fangcai.db.user}
    password: ${fangcai.db.pwd}

logging:
  level:
    cn.fangcai.*: debug

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn