server:
  servlet:
    context-path: /api
  port: 7000
spring:
  profiles:
    active: dev
  application:
    name: fangcai-blog-app

  jackson:
    date-format: yyyy-MM-dd HH:mm
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
