spring:
  datasource:
    url: jdbc:mysql://${fangcai.db.url}/${fangcai.db.name}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: ${fangcai.db.user}
    password: ${fangcai.db.pwd}
    hikari:
      max-lifetime: 5000
      connection-timeout: 30000
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 5000


logging:
  level:
    cn.fangcai.*: debug

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

wx:
  token: "test"