spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${fangcai.db.name}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: ${fangcai.db.user}
    password: ${fangcai.db.pwd}